version: '3.8'

services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672" # RabbitMQ port
  #     - "15672:15672" # Management UI port
  #   environment:
  #     RABBITMQ_DEFAULT_USER: root
  #     RABBITMQ_DEFAULT_PASS: 123123

  producer:
    build:
      context: .
      dockerfile: ./Producer/Dockerfile
    #container_name: producer
    # depends_on:
    #   - rabbitmq
    # environment:
    #   - RABBITMQ_HOST=rabbitmq
    #   - RABBITMQ_USER=root
    #   - RABBITMQ_PASS=123123
    networks:
      - app-network

  consumer:
    build:
      context: .
      dockerfile: ./Consumer/Dockerfile
    #container_name: consumer
    # depends_on:
    #   - rabbitmq
    # environment:
    #   - RABBITMQ_HOST=rabbitmq
    #   - RABBITMQ_USER=root
    #   - RABBITMQ_PASS=123123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
